version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  email-service:
    image: brando1607/email-service:latest
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
